// Generated by IcedCoffeeScript 1.3.3e
var RPC, Stream, uuid,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

uuid = require('uuid');

Stream = require('stream');

RPC = (function(_super) {

  __extends(RPC, _super);

  function RPC(local) {
    this.local = local;
    RPC.__super__.constructor.apply(this, arguments);
    this.readable = true;
    this.writable = true;
    this.waiting = {};
    this.remote = {};
    this.paused = false;
  }

  RPC.prototype.write = function(data) {
    var args, k, key, message, results, uid, _fn, _i, _len, _ref,
      _this = this;
    if (data === 'A') this.emit('data', JSON.stringify(Object.keys(this.local)));
    message = JSON.parse(data);
    switch (message.length) {
      case 1:
        _fn = function() {
          var key;
          key = k;
          return _this.remote[key] = function() {
            var args, cb, uid, _j;
            args = 2 <= arguments.length ? __slice.call(arguments, 0, _j = arguments.length - 1) : (_j = 0, []), cb = arguments[_j++];
            uid = uuid.generate();
            this.waiting[uid] = cb;
            message = JSON.stringify([uid, key, args]);
            this.emit('data', message);
          };
        };
        for (_i = 0, _len = message.length; _i < _len; _i++) {
          k = message[_i];
          _fn();
        }
        return this.emit('remote', this.remote);
      case 2:
        uid = message[0], results = message[1];
        (_ref = this.waiting)[uid].apply(_ref, results);
        return delete waiting[uid];
      case 3:
        uid = message[0], key = message[1], args = message[2];
        return local[key].apply(local, [args].concat(function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return port.send(JSON.stringify([uid, args]));
        }));
    }
  };

  RPC.prototype.pipe = function() {
    RPC.__super__.pipe.apply(this, arguments);
    return this.emit('data', 'A');
  };

  RPC.prototype.pause = function() {};

  RPC.prototype.resume = function() {};

  RPC.prototype.end = function(data) {};

  return RPC;

})(Stream);

module.exports = RPC;
